#!/usr/bin/env bash

# This checks if the script is executed with an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# This runs whoami command under the specified user
sudo -u "$1" whoami

