#!/usr/bin/env bash

# This fix permissions for nginx.conf
chmod 644 /etc/nginx/nginx.conf

# This modifies nginx.conf to run as nginx user
sed -i -E 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# This modify default server configuration to listen on port 8080
sed -i -E 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

# This stops Apache service gracefully
service apache2 stop

# This restart Nginx service
service nginx restart

